[package]
name = "zom-desktop"
version.workspace = true
edition.workspace = true
description = "桌面入口层：组合 engine、workspace、command 与 GPUI 外壳"

[[bin]]
name = "Zom"
path = "src/main.rs"

[dependencies]
zom-engine.workspace = true
zom-workspace.workspace = true
zom-command.workspace = true
zom-lsp.workspace = true
lsp-types.workspace = true
gpui.workspace = true
notify.workspace = true
crossbeam-channel.workspace = true
pulldown-cmark.workspace = true
ratex-parser.workspace = true
ratex-layout.workspace = true
ratex-svg.workspace = true
ratex-types.workspace = true
serde.workspace = true
serde_json.workspace = true
toml.workspace = true

[target.'cfg(target_os = "macos")'.dependencies]
cocoa.workspace = true

[target.'cfg(target_os = "windows")'.dependencies]
raw-window-handle.workspace = true
resvg.workspace = true
windows.workspace = true

[lints]
workspace = true
