[package]
name = "zcv-engine"
version.workspace = true
edition.workspace = true
description = "工业级纯粹文本编辑引擎底座"

[lib]
path = "src/engine.rs"

[dependencies]
regex.workspace = true
regex-automata.workspace = true
ropey.workspace = true
thiserror.workspace = true
unicode-segmentation.workspace = true
unicode-width.workspace = true

[dev-dependencies]
criterion.workspace = true

[[bench]]
name = "buffer_edits"
harness = false

[lints]
workspace = true
