[package]
name = "zom-engine"
version = "0.1.0"
edition = "2024"
description = "一个纯粹的、与用户界面无关的文本编辑引擎"

[dependencies]
thiserror = "2.0.18"

[dev-dependencies]
# 仅在测试和 examples 沙盒中使用 GPUI
gpui = "0.2.2"

[[example]]
name = "gpui_m1_testbed"
path = "examples/gpui_m1_testbed.rs"
[[example]]
name = "gpui_m2_testbed"
path = "examples/gpui_m2_testbed.rs"
