[workspace]
members = [
    "zom-engine",
    "zom-command",
    "zom-ai",
    "zom-workspace",
    "zom-desktop",
]
resolver = "3"

[workspace.package]
edition = "2024"

[workspace.dependencies]
zom-engine = { path = "zom-engine" }
zom-workspace = { path = "zom-workspace" }
zom-command = { path = "zom-command" }
zom-ai = { path = "zom-ai" }
