[package]
name = "zcv-text"
version.workspace = true
edition.workspace = true
description = "文本存储、快照、坐标、事务与历史内核"

[lib]
path = "src/text.rs"

[dependencies]
imara-diff.workspace = true
ropey.workspace = true
sum-tree.workspace = true
thiserror.workspace = true
unicode-segmentation.workspace = true
unicode-width.workspace = true

[lints]
workspace = true
