[package]
name = "zom-workspace"
version.workspace = true
edition.workspace = true
description = "工作区模型层：文件、缓冲区生命周期、路径绑定与保存边界"

[dependencies]
zom-engine.workspace = true
zom-lsp.workspace = true
lsp-types.workspace = true
serde_json.workspace = true
trash.workspace = true
ignore.workspace = true
tree-sitter.workspace = true
tree-sitter-rust.workspace = true
tree-sitter-toml-ng.workspace = true
tree-sitter-md.workspace = true
tree-sitter-json.workspace = true
tree-sitter-yaml.workspace = true
tree-sitter-bash.workspace = true
tree-sitter-html.workspace = true
tree-sitter-css.workspace = true
tree-sitter-typescript.workspace = true
tree-sitter-java.workspace = true
tree-sitter-python.workspace = true

[lints]
workspace = true
