[package]
name = "zcv-terminal"
version.workspace = true
edition.workspace = true
description = "嵌入式终端面板"

[lib]
path = "src/terminal.rs"

[dependencies]
alacritty_terminal.workspace = true
anyhow.workspace = true
async-channel.workspace = true
gpui.workspace = true
parking_lot.workspace = true
serde.workspace = true
serde_json.workspace = true
sysinfo.workspace = true
unicode-width.workspace = true
zcv-actions.workspace = true
zcv-project.workspace = true
zcv-settings.workspace = true
zcv-theme.workspace = true
zcv-ui.workspace = true
zcv-workspace.workspace = true

[target.'cfg(unix)'.dependencies]
libc.workspace = true

[dev-dependencies]
gpui = { workspace = true, features = ["test-support"] }
tempfile.workspace = true
zcv-assets.workspace = true

[lints]
workspace = true
