[package]
name = "zcv-project"
version.workspace = true
edition.workspace = true

[lib]
path = "src/project.rs"

[dependencies]
anyhow.workspace = true
async-channel.workspace = true
globset.workspace = true
gpui.workspace = true
futures.workspace = true
trash.workspace = true
zcv-text.workspace = true
zcv-fs-watch.workspace = true
zcv-git.workspace = true
zcv-language.workspace = true
zcv-multi-buffer.workspace = true

[dev-dependencies]
gpui = { workspace = true, features = ["test-support"] }
tempfile.workspace = true

[lints]
workspace = true
