[package]
name = "zcv-project"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
async-channel.workspace = true
crossbeam-channel.workspace = true
globset.workspace = true
gpui.workspace = true
log.workspace = true
notify.workspace = true
trash.workspace = true
zcv-buffer-diff.workspace = true
zcv-engine.workspace = true
zcv-git.workspace = true
zcv-language.workspace = true

[dev-dependencies]
gpui.workspace = true
tempfile.workspace = true

[lints]
workspace = true
