[package]
name = "zcv-picker"
version.workspace = true
edition.workspace = true
description = "通用搜索-选择器"

[lib]
path = "src/picker.rs"

[dependencies]
gpui.workspace = true
zcv-actions.workspace = true
zcv-theme.workspace = true
zcv-ui.workspace = true

[dev-dependencies]
zcv-editor.workspace = true
gpui = { workspace = true, features = ["test-support"] }

[lints]
workspace = true
