[package]
name = "zcv-ui"
version.workspace = true
edition.workspace = true

[lib]
path = "src/ui/mod.rs"

[dependencies]
gpui.workspace = true
zcv-keymap.workspace = true
zcv-theme.workspace = true

[dev-dependencies]
gpui = { workspace = true, features = ["test-support"] }

[lints]
workspace = true
