[package]
name = "zcv-preview"
version.workspace = true
edition.workspace = true
description = "文件预览协议与注册表"

[dependencies]
gpui.workspace = true
zcv-engine.workspace = true
zcv-editor.workspace = true
zcv-workspace.workspace = true

[dev-dependencies]
gpui.workspace = true

[lints]
workspace = true
