[package]
name = "zcv-editor"
version.workspace = true
edition.workspace = true
description = "可嵌入文本编辑组件"

[dependencies]
gpui.workspace = true
gpui-sum-tree.workspace = true
log.workspace = true
thiserror.workspace = true
unicode-segmentation.workspace = true
unicode-width.workspace = true
zcv-buffer-diff.workspace = true
zcv-engine.workspace = true
zcv-language.workspace = true
zcv-theme.workspace = true
zcv-ui.workspace = true
zcv-workspace.workspace = true

[dev-dependencies]
gpui.workspace = true

[lints]
workspace = true
